name: Deploy Lambda Functions and Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'
      - 'infrastructure/**'
      - '.github/workflows/deploy-lambda.yml'

  # Allow manual trigger
  workflow_dispatch:

env:
  CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
  CDK_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Build Lambda functions
      - name: Build transcribe Lambda
        working-directory: ./lambda/transcribe
        run: |
          npm install
          npm run build

      - name: Build analyze-transcript Lambda
        working-directory: ./lambda/analyze-transcript
        run: |
          npm install
          npm run build

      - name: Build analyze-common-pain-points Lambda
        working-directory: ./lambda/analyze-common-pain-points
        run: |
          npm install
          npm run build

      # Bootstrap CDK (if not already done)
      - name: Bootstrap CDK
        working-directory: ./infrastructure/cdk
        run: |
          npm ci
          npx cdk bootstrap aws://${{ env.CDK_DEFAULT_ACCOUNT }}/${{ secrets.AWS_REGION }}
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # Deploy CDK infrastructure
      - name: Deploy CDK infrastructure
        working-directory: ./infrastructure/cdk
        run: |
          npm install -g aws-cdk
          npm run build
          echo "Starting CDK deployment..."
          cdk deploy --require-approval never --verbose || {
            echo "CDK deployment failed"
            exit 1
          }
          echo "CDK deployment completed successfully"
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # Output SQS Queue URLs and save to file
      - name: Get SQS Queue URLs
        id: get-queue-urls
        if: success()
        run: |
          echo "Getting stack outputs..."
          aws cloudformation describe-stacks --stack-name PainpointLambdaStack --query "Stacks[0].Outputs" --output json > queue-outputs.json
          echo "Queue URLs have been saved to queue-outputs.json. Add these to your Vercel environment variables."

      # Upload queue URLs as artifact
      - name: Upload queue URLs
        uses: actions/upload-artifact@v4
        with:
          name: queue-urls
          path: queue-outputs.json 